experiment:
  name: CamVid
  group: optim/RTFormer
  continue_with_errors: False
  start_from_grid: 0
  start_from_run: 0
  logger: clearml
  tracking_dir: experiments
  entity: null
  excluded_files: "*.pth"
  search: optim # search method to use (optim or grid)
  direction: max # direction of the search (max or min)
  n_trials: 4 # number of trials to run

parameters:
  tags: [[]]
  # train, test, inference
  # phases: [[run]]
  phases: [[train, test]]
  dataset_interface: [wd/data/CamVidDatasetInterface]

  train_params:
    max_epochs: [500]
    initial_lr: [0.0001, 0.001]
    optimizer: [Adam]
    optimizer_params:
      weight_decay: [0]
    loss:
      name: [focal]
      params:
        gamma: [0, 2]
    seed: [42]
    zero_weight_decay_on_bias_and_bn: [True]
    average_best_models: [False]
    greater_metric_to_watch_is_better: [True]
    metric_to_watch: [JaccardIndex]
    early_stopping_patience: [50]

  aux_loss:
      name: [auxiliary_loss]
      params:
        aux_loss_coeff: [0.2, 0.5]
        aux_loss: 
          name: [focal]
          params:
            gamma: [0, 2]

  train_metrics:
    f1: &metric_params
      num_classes: &num_classes [32]
  test_metrics:
    jaccard: *metric_params
    conf_mat: *metric_params
    f1: *metric_params
    precision: *metric_params
    recall: *metric_params

  model:
    name: [wd/models/rtformer/RTFormer]
    params:
    
  dataset:
    root: ["/ext/datasets/CamVid"]
    train_loader_drop_last: [True]
    channels: [['R', 'G', 'B']]
    num_classes: [32]
    batch_size: [2]
    val_batch_size: [4]
    test_batch_size: [4]
    num_workers: [0]
    size: [[360, 480]]
    return_name: [True]

  test_callbacks:
    PerExampleMetricCallback:
      phase: [TEST_BATCH_END]
    SegmentationVisualizationCallback:
  val_callbacks: 
    SegmentationVisualizationCallback: 
      batch_idxs: [[4, 32]]


other_grids:
  - train_params:
      scheduler:
        name: [PolyLR]
        params:
          power: [2.0]