experiment:
  name: WDSE
  group: KD/TAKD/p2
  continue_with_errors: False
  start_from_grid: 0
  start_from_run: 0
  logger: clearml
  tracking_dir: null
  entity: null
  excluded_files: "*.pth"

parameters:
  tags: [[]]
  # train, test, inference
  # phases: [[run]]
  phases: [[train, test]]
  dataset_interface: [wd/data/WeedMapDatasetInterface]

  train_params:
    max_epochs: [500]
    initial_lr: [0.0001]
    optimizer: [Adam]
    optimizer_params:
      weight_decay: [0]
    loss:
      name: [wd/loss/loss/RMILoss]
      params:
        num_classes: [3]
    # ema: True
    seed: [42]
    zero_weight_decay_on_bias_and_bn: [True]
    average_best_models: [False]
    greater_metric_to_watch_is_better: [True]
    metric_to_watch: [f1]
    early_stopping_patience: [25]
    freeze_pretrained: [True]

  train_metrics:
    f1: &metric_params
      num_classes: &num_classes [3]
  test_metrics:
    jaccard: *metric_params
    conf_mat: *metric_params
    f1: *metric_params
    precision: *metric_params
    recall: *metric_params

  kd:
    module:
      name: [logits_distillation]
      params:

    teacher:
      name: [lawin]
      params:
        backbone: [MiT-B0]
        backbone_pretrained: [True]
        main_channels: [4]
        main_pretrained: [['R', 'G', 'G', 'G']]
        pretrained: 
          run: [freckled-chimpanzee-58]

    loss:
      name: [kd_logits_loss]
      params:
        distillation_loss:
          name: [vis_kldiv_loss]
        distillation_loss_coeff: [0.8]

  model:
    name: [lawin]
    params:
      backbone: [MiT-L0]
    
  dataset:
    root: ["dataset/4_rotations_processed_006_test/Sequoia"]
    train_folders: [['005', '007']]
    test_folders: [['006']]
    hor_flip: [True]
    ver_flip: [True]
    channels: [['R', 'G', 'NIR', 'RE']]
    batch_size: [6]
    val_batch_size: [12]
    test_batch_size: [12]
    num_workers: [0]
    num_classes: [3]
    return_path: [True]
    size: [same]
    crop_size: [same]

  test_callbacks:
    PerExampleMetricCallback:
      phase: [TEST_BATCH_END]
    SegmentationVisualizationCallback:
  val_callbacks: 
    SegmentationVisualizationCallback: 
      batch_idxs: [[4]]


other_grids:
  - kd:
      teacher:
        name: [lawin]
        params:
          backbone: [MiT-B0]
          backbone_pretrained: [True]
          main_channels: [4]
          main_pretrained: [['R', 'G', 'G', 'G']]
          pretrained: 
            run: [subspherical-littlenightmonkeys-25]

      loss:
        name: [kd_logits_loss]
        params:
          distillation_loss:
            name: [MSELoss]