experiment:
  name: WDSE
  group: cleaned/PSA/RMI_Aux
  continue_with_errors: False
  start_from_grid: 0
  start_from_run: 0
  logger: clearml
  tracking_dir: null
  entity: null
  excluded_files: "*.pth"

parameters:
  tags: [[]]
  # train, test, inference
  # phases: [[run]]
  phases: [[train, test]]
  dataset_interface: [wd/data/WeedMapDatasetInterface]

  train_params:
    max_epochs: [500]
    initial_lr: [0.01, 0.005]
    optimizer: [Adam]
    optimizer_params:
      weight_decay: [0]
    loss:
      name: [wd/loss/loss/RMILoss]
      params:
        num_classes: &num_classes [3]
    # ema: True
    seed: [42]
    zero_weight_decay_on_bias_and_bn: [True]
    average_best_models: [False]
    greater_metric_to_watch_is_better: [False]
    metric_to_watch: [loss/RMILoss]
    early_stopping_patience: [25]
    freeze_pretrained: [False]
    scheduler:
      name: [PolyLR]
      params:
        power: [2]

  aux_loss:
    name: [auxiliary_loss]
    params:
      aux_loss_coeff: [0.3]
      aux_loss: 
        name: [cross_entropy]
        params:

  train_metrics:
    f1: &metric_params
      num_classes: *num_classes
  test_metrics:
    jaccard: *metric_params
    conf_mat: *metric_params
    f1: *metric_params
    precision: *metric_params
    recall: *metric_params

  model:
    name: [wd/network/ocrnet/HRNet]
    params:
      pretrained: [True]
      side_pretrained: ['G']
      aux_output: [True]

  dataset:
    root: ["dataset/4_rotations_cleaned_005_test/Sequoia"]
    train_folders: [['006', '007']]
    test_folders: [['005']]
    hor_flip: [True]
    ver_flip: [True]
    channels: [['R', 'G', 'NIR', 'RE']]
    batch_size: [6]
    val_batch_size: [12]
    test_batch_size: [12]
    num_workers: [0]
    num_classes: [3]
    return_path: [True]
    size: [same]
    crop_size: [same]


  test_callbacks:
    PerExampleMetricCallback:
      phase: [TEST_BATCH_END]
    SegmentationVisualizationCallback:
      use_plotly: [True]
  val_callbacks: 
    SegmentationVisualizationCallback: 
      use_plotly: [True]
      batch_idxs: [[0, 1, 2, 3, 4]]


other_grids:
  - aux_loss:
      name: [auxiliary_loss]
      params:
        aux_loss: 
          name: [cross_entropy]
          params:
            weight: &weight [[0.0186, 1.0000, 3.9333]]
    train_params:
      loss:
        name: [wd/loss/loss/RMILoss]
        params:
          num_classes: [3]
          weight: *weight