experiment:
  name: WDRE
  group: KD/Continuation
  continue_with_errors: False
  start_from_grid: 0
  start_from_run: 0
  logger: clearml
  tracking_dir: null
  entity: null
  excluded_files: "*.pth"

parameters:
  tags: [[]]
  # train, test, inference
  # phases: [[run]]
  phases: [[train, test]]
  dataset_interface: [wd/data/WeedMapDatasetInterface]

  train_params:
    max_epochs: [500]
    initial_lr: [0.0001]
    optimizer: [Adam]
    optimizer_params:
      weight_decay: [0]
    loss:
      name: [wd/loss/loss/RMILoss]
      params:
        num_classes: [3]
        weight: [null, [0.0273, 1.0, 4.3802]]
    # ema: True
    seed: [42]
    zero_weight_decay_on_bias_and_bn: [True]
    average_best_models: [False]
    greater_metric_to_watch_is_better: [True]
    metric_to_watch: [f1]
    early_stopping_patience: [25]
    freeze_pretrained: [True]
    pass_context_to_loss: [True]

  train_metrics:
    f1: &metric_params
      num_classes: &num_classes [3]
  test_metrics:
    jaccard: *metric_params
    conf_mat: *metric_params
    f1: *metric_params
    precision: *metric_params
    recall: *metric_params

  kd:
    module:
      name: [logits_distillation]
      params:

    teacher:
      name: [wd/network/ocrnet/HRNet]
      params:
        pretrained: [mythopoeic-godwit-66]
        side_pretrained: ['G']
        aux_output: [False]
    loss:
      name: [wd/loss/loss/ContinuationLoss]
      params:
        max_epochs: [50, 100, 150]
        max_temperature: [9.0]
        margin: [5.0]

  model:
    name: [lawin]
    params:
      backbone: [MiT-L0]

  dataset:
    root: ["dataset/0_rotations_processed_003_test/RedEdge"]
    train_folders: [['000', '001', '002', '004']]
    test_folders: [['003']]
    hor_flip: [True]
    ver_flip: [True]
    channels: [['R', 'G', 'B', 'NIR', 'RE']]
    batch_size: [6]
    val_batch_size: [12]
    test_batch_size: [12]
    num_workers: [0]
    num_classes: [3]
    return_path: [True]
    size: [same]
    crop_size: [same]

  test_callbacks:
    PerExampleMetricCallback:
      phase: [TEST_BATCH_END]
    SegmentationVisualizationCallback:
  val_callbacks: 
    SegmentationVisualizationCallback: 
      batch_idxs: [[4]]


other_grids:

