experiment:
  name: WDRE
  group: test/PSA/HrnetPSAweeder/VariableLoss
  continue_with_errors: False
  start_from_grid: 0
  start_from_run: 0
  logger: clearml
  tracking_dir: null
  entity: null
  excluded_files: "*.pth"

parameters:
  tags: [[]]
  # train, test, inference
  # phases: [[run]]
  phases: [[train, test]]
  dataset_interface: [wd/data/WeedMapDatasetInterface]

  train_params:
    max_epochs: [500]
    optimizer: [Adam]
    optimizer_params:
      weight_decay: [0]
    loss:
      name: [wd/loss/loss/RMILoss]
      params:
        num_classes: [3]
        weight: [[0.0273, 1.0, 4.3802]]
    initial_lr: [0.01]
    scheduler:
      name: [ExpLR]
      params:
        gamma: [0.9]

    # ema: True
    seed: [42]
    zero_weight_decay_on_bias_and_bn: [True]
    average_best_models: [False]
    greater_metric_to_watch_is_better: [False]
    metric_to_watch: [RMILoss]
    freeze_pretrained: [False]

  aux_loss:
    name: [wd/loss/branch/BranchVariableLoss]
    params:
      min_threshold: [0.2]
      max_threshold: [1]
      aux_loss_weights: [[0.6, 0.2, 0.2]]
      aux_loss: 
        name: [cross_entropy]
        params:
          weight: [[0.0273, 1.0, 4.3802]]
      branch_loss: 
        name: [cross_entropy]
        params:
          weight: [[0.0273, 1.0, 4.3802]]
        
  early_stopping:
    patience: [25]
    monitor: [RMILoss]
    mode: [min]

  train_metrics:
    jaccard:
      num_classes: [3]
    f1:
      average: [macro]
      num_classes: [3]
      mdmc_average: [global]
  test_metrics:
    jaccard:
      num_classes: [3]
    conf_mat:
      num_classes: [3]
    f1:
      num_classes: [3]
      average: [macro]
      mdmc_average: [global]
    precision:
      average: [macro]
      num_classes: [3]
      mdmc_average: [global]
    recall:
      average: [macro]
      num_classes: [3]
      mdmc_average: [global]

  model:
    name: [wd/network/ocrnet/HRNetWeeder]
    params:
      pretrained: [True]
      side_pretrained: ['G']
      aux_output: [True]
      patch_dim: [2]
      num_heads: [4]
      embed_div: [1]
      emb_patch_div: [1]

  dataset:
    root: ["dataset/0_rotations_processed_003_test/RedEdge"]
    train_folders: [['000', '001', '002', '004']]
    test_folders: [['003']]
    hor_flip: [True]
    ver_flip: [True]
    channels: [['R', 'G', 'B', 'NIR', 'RE']]
    batch_size: [6]
    val_batch_size: [12]
    test_batch_size: [12]
    num_workers: [0]
    num_classes: [3]
    return_path: [True]
    size: [same]
    crop_size: [same]

  val_callbacks: 
    SegmentationVisualizationCallback:
  test_callbacks: 
    SegmentationVisualizationCallback:


other_grids:
