experiment:
  name: CamVid
  group: Lawin
  continue_with_errors: False
  start_from_grid: 0
  start_from_run: 0
  logger: clearml
  tracking_dir: null
  entity: null
  excluded_files: "*.pth"

parameters:
  tags: [[]]
  # train, test, inference
  # phases: [[run]]
  phases: [[train, test]]
  dataset_interface: [wd/data/CamVidDatasetInterface]

  train_params:
    max_epochs: [5000]
    initial_lr: [0.001, 0.0005, 0.0001]
    optimizer: [Adam]
    optimizer_params:
      weight_decay: [0]
    loss:
      name: [cross_entropy]
      params:
    seed: [42]
    zero_weight_decay_on_bias_and_bn: [True]
    average_best_models: [False]
    greater_metric_to_watch_is_better: [True]
    metric_to_watch: [JaccardIndex]

  early_stopping:
    check_finite: [False]
    patience: [50]
    mode: [max]

  train_metrics:
    f1: &metric_params
      num_classes: &num_classes [32]
  test_metrics:
    jaccard: *metric_params
    conf_mat: *metric_params
    f1: *metric_params
    precision: *metric_params
    recall: *metric_params

  model:
    name: [lawin]
    params:
      backbone: [MiT-B0, MiT-B1]
      backbone_pretrained: [True]

  dataset:
    root: ["/ext/datasets/CamVid"]
    train_loader_drop_last: [True]
    channels: [['R', 'G', 'B']]
    num_classes: [32]
    batch_size: [2]
    val_batch_size: [4]
    test_batch_size: [4]
    num_workers: [0]
    size: [[360, 480]]
    return_name: [True]

  test_callbacks:
    PerExampleMetricCallback:
      phase: [TEST_BATCH_END]
    SegmentationVisualizationCallback:
  val_callbacks: 
    SegmentationVisualizationCallback: 
      batch_idxs: [[4]]


other_grids:
